AllCops:
  TargetRubyVersion: 2.6
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
  rubocop: warning
Style/OptionalBooleanParameter:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'method_call']
